name: Deploy

on:
  push:
  workflow_dispatch:
    inputs:
      ref:
        description: The ref of site files repo.
        required: false
        default: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Checkout site files
      uses: actions/checkout@v2
      with:
        repository: MenciStaticSites/rqy-blog
        ref: ${{ github.event_name == 'push' && 'main' || github.event.inputs.ref }}
        path: site
    - name: Inject Service Worker
      uses: Menci/service-worker-redirect-origin@main
      with:
        www-root: site
        target-base-url: https://cdn-static.menci.xyz/rqy-blog/
    - name: Deploy to Static CDN
      uses: AyaInfra/StaticCDNDeploy@main
      with:
        deploy-credentials: ${{ secrets.STATIC_CDN_CREDENTIALS }}
        local-path: site
        remote-path: rqy-blog
    - name: Deploy to Azure
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
        action: upload
        app_location: site
        skip_app_build: true
        config_file_location: .
